# Generated by Django 5.1 on 2024-09-02 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Bank_sbi_PD', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('FD_sbi_PD', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('Bank_sbi_VK', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('FD_sbi_VK', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('Bank_kotak_VK', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('FD_kotak_VK', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('Bank_sbi_RK', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('FD_sbi_RK', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('Bank_indian_SR', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('FD_indian_SR', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('Bank_kotak_SR', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('FD_kotak_SR', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('Bank_kotak_RK_Sav', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('FD_kotak_RK_Sav', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('Bank_kotak_RK_Curr', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('Bank_kotak_Aad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('Bank_idfc_RK', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('FD_idfc_RK', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('lending', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('liquid_credit_due', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('lending_comm', models.CharField(default='', max_length=50)),
                ('total_assets', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=50, verbose_name='Application')),
                ('pan_user', models.CharField(choices=[('RK', 'RK'), ('SS', 'SS'), ('VK', 'VK'), ('PD', 'PD')], max_length=20, verbose_name='PAN User')),
                ('fund_name', models.CharField(max_length=255, verbose_name='Fund Name')),
                ('fund_type', models.CharField(choices=[('EQUITY', 'Equity'), ('DEBT', 'Debt'), ('HYBRID', 'Hybrid'), ('LIQUID', 'Liquid'), ('INDEX', 'Index'), ('ELSS', 'ELSS')], max_length=20, verbose_name='Fund Type')),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Investment Amount')),
                ('units_purchased', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Units Purchased')),
                ('returns', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Returns')),
                ('cagr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='CAGR (%)')),
                ('xirr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='XIRR (%)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('PENDING', 'Pending')], max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UPX_balance', models.CharField(max_length=100)),
                ('UPX_MX_balance', models.CharField(max_length=100)),
                ('UPX_funds', models.CharField(max_length=100)),
                ('UPX_MX_funds', models.CharField(max_length=100)),
                ('UPX_holding', models.CharField(max_length=100)),
                ('Zerodha_balance', models.CharField(max_length=100)),
                ('Zerodha_MX_balance', models.CharField(max_length=100)),
                ('Zerodha_funds', models.CharField(max_length=100)),
                ('Zerodha_MX_funds', models.CharField(max_length=100)),
                ('Zerodha_holding', models.CharField(max_length=100)),
                ('paytm_balance', models.CharField(max_length=100)),
                ('paytm_funds', models.CharField(max_length=100)),
                ('paytm_holding', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Investment Amount')),
                ('units_purchased', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Units Purchased')),
                ('NAV', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investment_date', models.DateTimeField(auto_now_add=True, verbose_name='Investment Date')),
                ('investment_type', models.CharField(choices=[('Onetime', 'Onetime'), ('SIP', 'SIP')], max_length=20, verbose_name='Investment Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='portfolio_app.mutualfund')),
            ],
        ),
    ]
