# Generated by Django 5.1 on 2024-09-02 06:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='total_assets',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='UPX_MX_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='UPX_MX_funds',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='UPX_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='UPX_funds',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='UPX_holding',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='Zerodha_MX_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='Zerodha_MX_funds',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='Zerodha_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='Zerodha_funds',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='Zerodha_holding',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='paytm_balance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='paytm_funds',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='paytm_holding',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15),
        ),
    ]
